drop table if exists bookmarks;
create table bookmarks (
  id INTEGER primary key generated by default as identity,
  title text not null,
  description text,
  rating numeric not null,
  url text not null
);

insert into bookmarks (title, description, rating, url)
values ('Thinkful', 'Coding Bootcamp', 5, 'https://www.thinkful.com/'),
  ('Google', 'Search Engine', 5, 'https://www.google.com/'),
  ('Yahoo', '', 3, 'https://www.yahoo.com/'),
  ('Bing', '', 4, 'https://www.bing.com/'),
  ('Twitter', 'Share news', 5, 'https://www.twitter.com/'),
  ('Facebook', 'Share about your life', 3, 'https://www.facebook.com/'),
  ('Instagram', 'Share pictures and videos', 5, 'https://www.instagram.com/'),
  ('Wikipedia', 'Learn about anything', 4, 'https://www.wikipedia.org/'),
  ('Netflix', 'Watch movies and tv series', 4, 'https://www.netflix.com/'),
  ('Slack', 'Communication with your coworkers', 5, 'https://slack.com/')